plugins { id 'com.android.application' }

android {
    namespace 'com.openai.hanghae.mini'
    compileSdk 35

    defaultConfig {
        minSdk 23
        targetSdk 35
        versionCode 10015
        versionName '1.0.15'
    }

    flavorDimensions 'edition'
    productFlavors {
        distribution {
            dimension 'edition'
            applicationId 'com.navigator.freedom.miniicon'
            buildConfigField 'boolean', 'NAVIGATOR_EDITION', 'false'
        }
        navigator {
            dimension 'edition'
            applicationId 'com.navigator.freedom.navigatoricon'
            buildConfigField 'boolean', 'NAVIGATOR_EDITION', 'true'
        }
    }

    buildFeatures { buildConfig true }

    buildTypes {
        debug { debuggable false; minifyEnabled false }
        release { minifyEnabled false; shrinkResources false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
